# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 03:25
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import drive_app.models
import easy_thumbnails.fields
import sanitizer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', sanitizer.models.SanitizedCharField(max_length=48, validators=[django.core.validators.MinLengthValidator(3, message='Field value must be at least 3 characters long')])),
                ('last_name', sanitizer.models.SanitizedCharField(max_length=48, validators=[django.core.validators.MinLengthValidator(3, message='Field value must be at least 3 characters long')])),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', drive_app.models.DriveUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', sanitizer.models.SanitizedCharField(max_length=256, validators=[django.core.validators.RegexValidator('^[\\.0-9a-zA-Z_]*$', 'Only alphanumeric characters are allowed.'), django.core.validators.MinLengthValidator(3, message='Field value must be at least 3 characters long')])),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='drive_app.Folder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', sanitizer.models.SanitizedCharField(max_length=256, validators=[django.core.validators.MinLengthValidator(3, message='Field value must be at least 3 characters long')])),
                ('size', models.IntegerField(default=0)),
                ('file', models.ImageField(upload_to=b'')),
                ('thumbnail', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='thumbnails')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='drive_app.Folder')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiscFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', sanitizer.models.SanitizedCharField(max_length=256, validators=[django.core.validators.MinLengthValidator(3, message='Field value must be at least 3 characters long')])),
                ('size', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to=drive_app.models.user_directory_path)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='drive_app.Folder')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set([('owner', 'name')]),
        ),
    ]
