# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 02:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import drive_app.models
import sanitizer.models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driveuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='driveuser',
            managers=[
                ('objects', drive_app.models.DriveUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='driveuser',
            name='added',
        ),
        migrations.RemoveField(
            model_name='driveuser',
            name='username',
        ),
        migrations.AddField(
            model_name='driveuser',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='driveuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='driveuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='driveuser',
            name='first_name',
            field=sanitizer.models.SanitizedCharField(max_length=48, validators=[django.core.validators.MinLengthValidator(3, message='Field value must be at least 3 characters long')]),
        ),
        migrations.AlterField(
            model_name='driveuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='driveuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driveuser',
            name='last_name',
            field=sanitizer.models.SanitizedCharField(max_length=48, validators=[django.core.validators.MinLengthValidator(3, message='Field value must be at least 3 characters long')]),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=sanitizer.models.SanitizedCharField(max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'Only alphanumeric characters are allowed.'), django.core.validators.MinLengthValidator(3, message='Field value must be at least 3 characters long')]),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=sanitizer.models.SanitizedCharField(max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'Only alphanumeric characters are allowed.'), django.core.validators.MinLengthValidator(3, message='Field value must be at least 3 characters long')]),
        ),
    ]
