# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 21:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import sanitizer.models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=sanitizer.models.SanitizedCharField(max_length=256, validators=[django.core.validators.RegexValidator('^[\\.0-9a-zA-Z_]*$', 'Only alphanumeric characters are allowed.'), django.core.validators.MinLengthValidator(3, message='Field value must be at least 3 characters long')]),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=sanitizer.models.SanitizedCharField(max_length=256, validators=[django.core.validators.RegexValidator('^[\\.0-9a-zA-Z_]*$', 'Only alphanumeric characters are allowed.'), django.core.validators.MinLengthValidator(3, message='Field value must be at least 3 characters long')]),
        ),
    ]
